name: Deploy via SFTP

on:
  push:
    branches:
      - main  # SpustÃ­ se pÅ™i kaÅ¾dÃ©m pushi na vÄ›tev main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: â¬‡ï¸ Checkout repository
        uses: actions/checkout@v3

      - name: ğŸ§ª Build project
        run: |
          echo "Add your build steps here if needed"
       

      - name: ğŸš€ Deploy via SFTP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SFTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 22         
          target: "/www/" 
